version: '3.1'
services:
  dawa:
    container_name: dawa_ws
    image: 'dawa_ws_image:latest'
    restart: always
    ports:
      - '1008:5000'
    volumes:
      - /home/victor/Documentos/data/LOGS/dawa_ws:/app/dawa/src/utils/general/LOGS