version: '3.1'
services:
  proyecto_front:
    container_name: proyecto_parcial_front
    image: 'dawa_ws_image:latest'
    restart: always
    ports:
      - '1008:1011'
    volumes:
      - /home/victor/Documentos/ProyectosPython/LOGS:/proyecto-final/ws_dawa/src/utils/general/LOGS

  proyecto_back:
    container_name: proyecto_parcial_back
    image: 'dawa_ws_image:latest'
    restart: always
    ports:
      - '9002:5000'
    volumes:
      - /home/victor/Documentos/ProyectosPython/LOGS:/proyecto-final/ws_dawa/src/utils/general/LOGS

  db:
    container_name: proyecto_parcial_base
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - '5432:5432'
    volumes:
      - /home/victor/Documentos/ProyectosPython/LOGS:/proyecto-final/ws_dawa/src/utils/general/LOGS